### ISSUE TITLE
Tiny thing: Update Release Notes

### ISSUE THREAD

**Issue by behinger** [beacon-biosignals/PyMNE.jl#14]
Could you update the release notes of 0.2.0 that `get_info` was removed?

Took us a while to figure that one out... :S

**Comment by vladdez** [comment]
And it would be great to know what do you use now instead of it

**Comment by vladdez** [comment]
btw we solved our issue by using raw.info instead of get_info(raw) and pyconvert
`pos = PyMNE.channels.make_eeg_layout(raw.info).pos
pos = pyconvert(Matrix, pos)`

**Comment by palday** [comment]
@vladdez you don't need `get_info` anymore because PythonCall doesn't over-zealously convert all subtypes of Python `dict` to Julia `Dict`. That conversion under PyCall was the cause of the problem -- MNE wanted `Info` but got `dict` when round-tripping.

**Comment by palday** [comment]
done
